config/routes.rb
Rails.application.routes.draw do
  resources :microposts,          only: [:create, :destroy]

  get 'sessions/new'

  resources :users
  get '/signup',     to: 'users#new'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root                'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help',    to: 'static_pages#help'
  get '/links',   to: 'static_pages#links'
  get '/members', to: 'static_pages#members'
  get '/sitemap', to: 'static_pages#sitemap'
  get '/staff',   to: 'static_pages#staff'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def contact
  end

  def help
  end

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def links
  end

  def members
  end

  def sitemap
  end

  def staff
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div class="container-fluid" id="main">
<div class="row">

<h1>About</h1>

</div> <!-- row -->
</div> <!-- container-fluid main -->

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="container-fluid" id="main">
<div class="row">

<h1>Contact</h1>

</div> <!-- row -->
</div> <!-- container-fluid main -->

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="container-fluid" id="main">
<div class="row">

<h1>Help</h1>

</div> <!-- row -->
</div> <!-- container-fluid main -->

app/views/static_pages/home.html.erb
<div class="container-fluid" id="main">

<% if logged_in? %>

  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div> <!-- row -->

<% else %>

  <div class="row">
    <div class="col-sm-6 col-md-6 col-lg-3" style= "padding: 0;">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="//youtube.com/embed/h3ruZwwpbgk?1&loop=1&playlist=h3ruZwwpbgk" 
          allowfullscreen name="iframe_a"></iframe>
      </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-3" style= "padding: 0;">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="//youtube.com/embed/sUW41slxvrw?1&loop=1&playlist=sUW41slxvrw" 
          allowfullscreen name="iframe_a"></iframe>
      </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-3" style= "padding: 0;">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="//youtube.com/embed/NUsoVlDFqZg?1&loop=1&playlist=NUsoVlDFqZg" 
          allowfullscreen name="iframe_a"></iframe>
      </div>
    </div>
    <div class="col-sm-6 col-md-6 col-lg-3" style= "padding: 0;">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="//youtube.com/embed/TyHvyGVs42U?1&loop=1&playlist=TyHvyGVs42U" 
          allowfullscreen name="iframe_a"></iframe>
      </div>
    </div>
  </div> <!-- row -->

<% end %>

</div> <!-- container-fluid main -->

app/views/static_pages/links.html.erb
<% provide(:title, "Links") %>
<div class="container-fluid" id="main">
<div class="row">

<h1>Links</h1>

</div> <!-- row -->
</div> <!-- container-fluid main -->

app/views/static_pages/members.html.erb
<% provide(:title, "Members") %>
<div class="container-fluid" id="main">
<div class="row">

<h1>Members</h1>

</div> <!-- row -->
</div> <!-- container-fluid main -->

app/views/static_pages/sitemap.html.erb
<% provide(:title, "Sitemap") %>
<div class="container-fluid" id="main">
<div class="row">

<h1>Sitemap</h1>

</div> <!-- row -->
</div> <!-- container-fluid main -->

app/views/static_pages/staff.html.erb
<% provide(:title, "Staff") %>
<div class="container-fluid" id="main">
<div class="row">
  
  <h1>Staff</h1>
  
  <h2>Admin: Zvonimir Kolumbic</h2>

  <nav class="navbar navbar-default">
    <%= link_to "All users", users_path, class: "btn btn-default btn-xs" %>
    <%= link_to "New User", new_user_path, class: "btn btn-default btn-xs" %>
  <nav/>

<br /><br />

</div> <!-- row -->
</div> <!-- container-fluid main -->