config/routes.rb
Rails.application.routes.draw do
  resources :microposts,          only: [:create, :destroy]

  get 'sessions/new'

  resources :users
  get '/signup',     to: 'users#new'
  get '/login',      to: 'sessions#new'
  post '/login',     to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  root                'static_pages#home'
  get '/about',   to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/help',    to: 'static_pages#help'
  get '/links',   to: 'static_pages#links'
  get '/members', to: 'static_pages#members'
  get '/sitemap', to: 'static_pages#sitemap'
  get '/staff',   to: 'static_pages#staff'

end

app/views/layouts/_footer.html.erb
<div class="container-fluid" id="footer">

<div class="row">
<hr>
  <nav class="navbar navbar-default">
      <%= link_to "<span class=\"glyphicon glyphicon-home\"></span>".html_safe, root_path, 
        class: "btn btn-default navbar-btn btn-xs" %>
      <%= link_to "About", about_path, class: "btn btn-default btn-xs" %> 
      <%= link_to "Help", help_path, class: "btn btn-default btn-xs" %>
      <%= link_to "Sitemap", sitemap_path, class: "btn btn-default btn-xs" %>
      <%= link_to "Staff", staff_path, class: "btn btn-default btn-xs" %>
      <%= link_to "Links", links_path, class: "btn btn-default btn-xs" %>
      <%= link_to "<span class=\"glyphicon glyphicon-envelope\"></span>".html_safe,contact_path, 
        class: "btn btn-default btn-xs" %>
    <div class="navbar-header pull-right">
      <%= link_to "Cornerstone", root_path, class: "navbar-brand" %>
      <%= link_to image_tag("luka.jpg", alt: "My grandson Luka"), root_path, 
        class: "navbar-brand", style: "padding: 0px;" %>
    </div>
  </nav>
<hr>
</div> <!-- row --> 

<div class="row">
  <p style="text-align: center;">Ivan Dolac, 2018</p>  
</div> <!-- row --> 

</div> <!-- container-fluid footer -->

app/views/layouts/_header.html.erb
<div class="container-fluid" id="header">
<div class="row">
<hr>
<nav class="navbar navbar-default">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <%= link_to image_tag("luka.jpg", alt: "My grandson Luka"), root_path, 
      class: "navbar-brand", style: "padding: 0px;" %>
    <%= link_to "Cornerstone", root_path, class: "navbar-brand" %>
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
      data-target="#collapse-1" aria-expanded="false" style="margin-right: 0px;">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="collapse-1">
    <ul class="nav navbar-nav">
        <% if logged_in? %>
          <li><%= link_to "Users", users_path, class: "btn btn-default btn-lg" %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle btn btn-default btn-lg" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path, class: "btn btn-default btn-lg"%></li>
        <% end %>
      </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Sign up", signup_path, class: "btn btn-default btn-lg"%></li>
      <li><%= link_to "Contact", contact_path, class: "btn btn-default btn-lg" %></li>
      <li class="dropdown">
          <a href="#" class="dropdown-toggle btn btn-default btn-lg" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">Go to<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Help", help_path %></li>
            <li><%= link_to "Sitemap", sitemap_path %></li>
            <li><%= link_to "Staff", staff_path %></li>
            <li><%= link_to "Links", links_path %></li>
          </ul>
      </li> <!-- dropdown  -->
    </ul>
  </div> <!-- navbar-collapse -->

</nav> <!-- navbar navbar-default -->
<hr>
</div> <!-- row -->
</div> <!-- container-fluid header -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta name="description" content="Web projects development aid: Ruby on Rails, 
    Bootstrap (Navbar navigation, Responsive embed of Youtube videos), HTML, CSS.">
  <meta name="keywords" content="static pages, YouTube videos, source code: Ruby on Rails, 
    Bootstrap, HTML, CSS">
  <meta name="author" content="Zvonimir Kolumbic">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>